### ISSUE TITLE
Why random frequency on each transmission cycle?

### ISSUE THREAD

**Issue by danielcharrua** [IgrikXD/WSPR-beacon#9]
Hello, I'm trying to understand this:

> Each transmission cycle is performed at a randomly selected frequency within a range of +/- 100 Hz from the center frequency.

Can you explain why?
Thank you.

**Comment by IgrikXD** [comment]
> Hello, I'm trying to understand this:
> 
> > Each transmission cycle is performed at a randomly selected frequency within a range of +/- 100 Hz from the center frequency.
> 
> Can you explain why? Thank you.

Good afternoon! This is done to **prevent potential collisions with other WSPR transmitters operating on the same frequency** as the one used by your device for message transmission. According to the standard, WSPR messages can be transmitted within a 200 Hz bandwidth for each operational band. Using the central operating frequency, we randomly select a transmission frequency within ±100 Hz of the central frequency during each transmission cycle. This approach ensures reliable transmission of a series of WSPR messages, even in cases where some transmitted messages collide with signals from other WSPR beacons.

Best regards, Ihar Yatsevich
